#! /bin/sh

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config border_width 2
bspc config focused_border_color \#0A6CF5
# bspc config focused_border_color \#D23D3D

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a audio state=floating rectangle=1200x600+400+250
bspc rule -a settings state=floating rectangle=1200x600+400+250
bspc rule -a "MATLAB R2021b - academic use" state=floating

[ "$1" = 0 ] && wmname LG3D

~/.config/bspwm/autorun.sh
